services:
  bareiron:
    build: .
    container_name: bareiron
    ports:
      - "25565:25565"
    volumes:
      - ./:/app:rw
    restart: unless-stopped
    stdin_open: true
    tty: true
    network_mode: bridge
